<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_BusinessUnits</name>
   <tag></tag>
   <elementGuidId>bd3a1b5b-55bc-4535-8933-315535ed4ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/ul/div/div/a[10]/text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55ff8b43-307a-411f-bae5-9a72e2384452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headerText</value>
      <webElementGuid>b0947878-b195-4be1-980f-12c1c6fc4284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Business Units</value>
      <webElementGuid>0c74cefb-fb1a-4fff-b050-2ebab3378010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;wrapper d-flex flex-column min-vh-100&quot;]/div[@class=&quot;body flex-grow-1 px-3&quot;]/div[@class=&quot;sidebar sidebar-fixed&quot;]/ul[@class=&quot;sidebar-nav&quot;]/div[@class=&quot;container-fluid&quot;]/div[1]/a[@class=&quot;menuLink&quot;]/text[@class=&quot;headerText&quot;]</value>
      <webElementGuid>992118d3-3acb-4821-a95c-51874ae3ac98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/ul/div/div/a[10]/text</value>
      <webElementGuid>d69575a8-125b-46a6-8cec-2b7306acf11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::text[1]</value>
      <webElementGuid>af36d332-4389-46d0-8592-8ca7f29117a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[1]/following::text[2]</value>
      <webElementGuid>eeec96d2-4569-477e-b57d-4c721ee9ed79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Groups'])[1]/preceding::text[1]</value>
      <webElementGuid>629930ca-d9b9-44ad-a562-a6f43854e88b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPLICATION FINDINGS BY TYPE'])[1]/preceding::text[2]</value>
      <webElementGuid>37f63a2d-1dc7-4351-9c91-12e2df97975e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Business Units']/parent::*</value>
      <webElementGuid>11e79f70-2e2d-491e-930e-58de82977fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[10]/text</value>
      <webElementGuid>a5faca5d-11e8-44ef-88bf-7207e2d84b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = 'Business Units' or . = 'Business Units')]</value>
      <webElementGuid>f5a62185-44ed-4b20-85ec-2808b602bcf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
