<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload the project zip</name>
   <tag></tag>
   <elementGuidId>6f66ef4c-e48f-4dbf-81bb-36a94d86fbe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputFile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputFile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e49d537-df20-49da-a6af-58b3d68dfd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm white-input</value>
      <webElementGuid>f0906c4f-04c2-4145-956e-18a573c2ec59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputFile</value>
      <webElementGuid>cae30113-8cc0-4a22-9440-62972173704e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>da04e09b-e3ae-4dd1-9026-7adaf2752bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Upload the project zip file</value>
      <webElementGuid>141a7253-4cbe-4402-be6a-e6b51693d41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>d5dba22a-3449-4488-be15-1638aa78ff4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/zip</value>
      <webElementGuid>d24771d6-ab0a-43fc-a0b0-80b579ab1c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputFile&quot;)</value>
      <webElementGuid>723af477-c543-4420-a627-251a4865ba98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputFile']</value>
      <webElementGuid>199a1fae-f6e2-4085-b713-bf9c4a35306c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[3]/input</value>
      <webElementGuid>a03711e0-e9e1-4f4f-8aea-89a01666f696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>7f089d3b-e527-4d69-a6a1-6a233a4f8ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputFile' and @type = 'file' and @placeholder = 'Upload the project zip file']</value>
      <webElementGuid>6cea02a2-b95b-4764-b1b3-deda4104ef5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
