<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_select Application</name>
   <tag></tag>
   <elementGuidId>223e103a-7ff0-448a-809d-d8a46dbad94c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scanType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='scanType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a76b0b5c-9446-4cd6-8d02-9ebb7252b6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scanType</value>
      <webElementGuid>c4c950d1-f930-463f-b56f-3ddee03746cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select white-input</value>
      <webElementGuid>4cd565a1-ae36-4edf-995c-e8f43eb68ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Website Application</value>
      <webElementGuid>4a0b9fdf-e0c6-4b9c-b458-4f91f85bdf97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scanType&quot;)</value>
      <webElementGuid>de4eeac5-3280-4970-b498-3cb11806e2f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='scanType']</value>
      <webElementGuid>5f8f4a27-b604-40de-a98f-417703b08090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[2]/select</value>
      <webElementGuid>e47b2bd9-79bf-4351-ad30-ba95ecdbb93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select application'])[1]/following::select[1]</value>
      <webElementGuid>05f417d8-6720-40c8-a8f3-67d504b55f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan Name'])[1]/following::select[1]</value>
      <webElementGuid>63068e9c-1470-49a1-8037-a93be3e53ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload the project zip file'])[1]/preceding::select[1]</value>
      <webElementGuid>3c1d5c57-a2ba-452f-a099-bd7f16d7424f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Scan'])[1]/preceding::select[1]</value>
      <webElementGuid>0e27c159-6b13-43c1-a78f-de506eff1772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ac92285f-30a4-4786-9127-e8ad9ac08b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'scanType' and (text() = 'Website Application' or . = 'Website Application')]</value>
      <webElementGuid>74759573-d938-4575-80c0-73122e17c3da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
