<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BusinessUnit</name>
   <tag></tag>
   <elementGuidId>5ebbe86b-c9ec-494b-9a52-8a90732079d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessUnit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='businessUnit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>076eeb20-4bd6-4412-ac54-79ae07639383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessUnit</value>
      <webElementGuid>ed1922df-e74d-4e05-aae3-81bbb271457d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select white-input</value>
      <webElementGuid>84a854cc-b833-40c8-a494-ea252320f5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectTestBusinessUnit</value>
      <webElementGuid>40472c0f-34aa-4ce5-a8ec-1b33a848eff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessUnit&quot;)</value>
      <webElementGuid>b9c49e3e-b5de-4965-9157-8a84570425cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='businessUnit']</value>
      <webElementGuid>65038dad-aff0-4179-bd62-a8f45a903815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[3]/select</value>
      <webElementGuid>61efcdee-9a82-446a-b528-32f0fa334f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Unit'])[1]/following::select[1]</value>
      <webElementGuid>f4ffb13e-95b7-4230-aff3-3de9976649f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Type'])[1]/following::select[2]</value>
      <webElementGuid>3c675e0d-6ed6-492c-8b03-3b4bcda76acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Group'])[1]/preceding::select[1]</value>
      <webElementGuid>86c79193-f5b7-494d-accb-88e2d26c9314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Owner'])[1]/preceding::select[2]</value>
      <webElementGuid>9c326cd7-5dbe-4b17-b52b-982f57f18136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>3124ec9a-a998-4b60-bd37-4c4e29ef0b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'businessUnit' and (text() = 'Please selectTestBusinessUnit' or . = 'Please selectTestBusinessUnit')]</value>
      <webElementGuid>1c092ea9-1ffd-4521-b284-86cc87d9d94a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
