<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Applicationtype</name>
   <tag></tag>
   <elementGuidId>a7419751-0453-448a-b37b-fdf95491aeef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#applicationType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='applicationType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6b00baad-47ff-40e6-9f44-9fc885452c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>applicationType</value>
      <webElementGuid>c56aca79-beea-49ca-82e7-b17e94444b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select white-input</value>
      <webElementGuid>1e5b72d8-0102-41e8-b866-ceba00ffbb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectWebsiteDesktop ApplicationMobile ApplicationWeb ServiceOthers</value>
      <webElementGuid>3380200e-4357-42f4-b2b5-0e38eecd1f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;applicationType&quot;)</value>
      <webElementGuid>dd263793-1343-43d9-bf21-22b3bca11380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='applicationType']</value>
      <webElementGuid>20e6c043-ecbb-4a49-b943-6c9b10b36124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[2]/select</value>
      <webElementGuid>d795989c-4662-4c41-bbb3-f95d31056c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Type'])[1]/following::select[1]</value>
      <webElementGuid>e33273bb-f561-49df-928a-abb91bcf87a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Name'])[1]/following::select[1]</value>
      <webElementGuid>a48d0f14-2b47-4368-a606-ac4df9fd72e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Unit'])[1]/preceding::select[1]</value>
      <webElementGuid>21fdc89b-e072-482a-9abc-bd08887185ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Group'])[1]/preceding::select[2]</value>
      <webElementGuid>514598d8-e30e-4947-8691-8951248cae70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>caa6c957-e889-44dd-bd94-7f6a5323d857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'applicationType' and (text() = 'Please selectWebsiteDesktop ApplicationMobile ApplicationWeb ServiceOthers' or . = 'Please selectWebsiteDesktop ApplicationMobile ApplicationWeb ServiceOthers')]</value>
      <webElementGuid>bbb91670-9920-49d1-889e-d36f9bf49a15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
