<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TestingStatus</name>
   <tag></tag>
   <elementGuidId>b9ab3031-a83a-46db-8832-25e1fa4df488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#testingStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='testingStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9ae279ce-18dd-45b9-bc3b-f64fec944f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>testingStatus</value>
      <webElementGuid>addab6c5-4033-43ea-a434-aa474c058ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select white-input</value>
      <webElementGuid>4699dc4b-e7d2-42c1-a15e-996060ae1007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YET TO STARTIN PROGRESSCOMPLETEDUNDER REVIEW</value>
      <webElementGuid>5db4f96e-84bc-42cd-a16b-824170380fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;testingStatus&quot;)</value>
      <webElementGuid>93f2f130-b8b4-42af-a678-7eb69e3ed5b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='testingStatus']</value>
      <webElementGuid>adb8a86e-2327-4369-83e3-a215f470e740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[7]/select</value>
      <webElementGuid>2329792d-90e9-48c8-a408-83a210ce5542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing Status'])[1]/following::select[1]</value>
      <webElementGuid>d286dac5-9af5-4008-bf54-76dd91532f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Impact'])[1]/following::select[2]</value>
      <webElementGuid>ed7f788e-9c8c-4b89-a286-6bc40e754d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='URL'])[1]/preceding::select[1]</value>
      <webElementGuid>cee4f7e3-b6e1-4cdd-ae02-fc2421d929e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Host'])[1]/preceding::select[1]</value>
      <webElementGuid>751c64f5-8af3-4b19-8089-cb9e866b2aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>66af062f-4259-40c0-bf23-f008b11f66f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'testingStatus' and (text() = 'YET TO STARTIN PROGRESSCOMPLETEDUNDER REVIEW' or . = 'YET TO STARTIN PROGRESSCOMPLETEDUNDER REVIEW')]</value>
      <webElementGuid>ff87bcf1-4e98-49f0-9d0b-98c7a053993b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
