<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AssetGroup</name>
   <tag></tag>
   <elementGuidId>a9a87f48-8cc7-4e8e-910c-a18e0098eda9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#assetGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='assetGroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d2d5886f-02a6-46bf-b09d-704a4c85e917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assetGroup</value>
      <webElementGuid>b2cb4288-7965-4bbe-8c1b-7614bb34a345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select white-input</value>
      <webElementGuid>d8a5b49b-9c02-4373-b6e8-53741b1eaa97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectTestAssetGroup</value>
      <webElementGuid>95b1d121-daba-4c10-97dc-66b0cd9a0802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assetGroup&quot;)</value>
      <webElementGuid>cad85b3c-b006-4a6a-bd18-f154b78d444f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='assetGroup']</value>
      <webElementGuid>1f9fc8dc-5e45-46e7-8854-8a5e3baabe7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[4]/select</value>
      <webElementGuid>d6b0c157-87c3-4e69-a664-02f8055cdd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Group'])[1]/following::select[1]</value>
      <webElementGuid>cbdd349c-aab0-4400-913c-eb924032bb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Unit'])[1]/following::select[2]</value>
      <webElementGuid>f776467f-ba30-4e6f-831d-49a76423958d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Owner'])[1]/preceding::select[1]</value>
      <webElementGuid>9ec1e48d-3aef-4f4e-8637-234c08a20b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Impact'])[1]/preceding::select[2]</value>
      <webElementGuid>9e22185b-36f8-4ddb-884a-c429219de861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>cf87f9f3-80e1-4057-b56c-b775ef52f916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'assetGroup' and (text() = 'Please selectTestAssetGroup' or . = 'Please selectTestAssetGroup')]</value>
      <webElementGuid>33ad9afd-27f3-4bba-aa4e-5d7df7c2eed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
