<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BusinessOwner</name>
   <tag></tag>
   <elementGuidId>07f7d381-74f7-43bc-b231-29704d55addf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessOwner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='businessOwner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d60529fa-c5ef-4703-a4df-4b1bb74fe469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessOwner</value>
      <webElementGuid>fb980de9-c580-4743-b1ee-a2a7abeca0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select white-input</value>
      <webElementGuid>d3a41bd5-3587-4ca7-94d1-278970e2eb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectTest QA Intrucept (testorganization@intrucept.com)</value>
      <webElementGuid>6be13b7f-19f9-4d63-8833-f4fc97950df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessOwner&quot;)</value>
      <webElementGuid>e4235452-5c3c-4f38-9273-a30fd301d8d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='businessOwner']</value>
      <webElementGuid>c7b9bb3e-6908-44b8-b972-28eef181bb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[5]/select</value>
      <webElementGuid>886b5f30-ccd4-406d-9857-b5f909c99751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Owner'])[1]/following::select[1]</value>
      <webElementGuid>6bf25222-9864-44ea-8974-e3195f4bd47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Group'])[1]/following::select[2]</value>
      <webElementGuid>ff92eac0-c943-4f60-8c0c-12eb7b060e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Impact'])[1]/preceding::select[1]</value>
      <webElementGuid>a69dcc0d-5bc3-47cb-beda-a7ef030fa07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing Status'])[1]/preceding::select[2]</value>
      <webElementGuid>e8626676-c815-4fca-8859-6202b5cc0342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>f4a475e8-9add-484c-9b1d-a39662de38b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'businessOwner' and (text() = 'Please selectTest QA Intrucept (testorganization@intrucept.com)' or . = 'Please selectTest QA Intrucept (testorganization@intrucept.com)')]</value>
      <webElementGuid>8dfd89af-0e9c-48de-8596-85bc78408e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
