<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BusinessImpact</name>
   <tag></tag>
   <elementGuidId>308c51d3-68d3-400b-9a61-7f03d2408ccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessImpact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='businessImpact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bf84d9d6-975f-442a-abd5-7522970e241e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessImpact</value>
      <webElementGuid>fac660c8-2c6c-4a05-9c6b-322932442b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select white-input</value>
      <webElementGuid>d03304e9-d2c6-40db-b2e7-d432c76b5c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectLOWMEDIUMHIGHCRITICAL</value>
      <webElementGuid>3cab34ba-d4c2-4fc4-b535-ebb3ae1b9c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessImpact&quot;)</value>
      <webElementGuid>d29d5878-4cce-4f9f-9bc1-871080d10ac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='businessImpact']</value>
      <webElementGuid>038136a9-a4b6-4583-8dda-1453c386dd05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[6]/select</value>
      <webElementGuid>f90a417f-458b-4a2e-b5f6-41ad10e2bcd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Impact'])[1]/following::select[1]</value>
      <webElementGuid>799de74e-5562-4950-b854-0b4569e4374a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Owner'])[1]/following::select[2]</value>
      <webElementGuid>ed81cc0d-3c68-48e5-81da-1b9e6d1aee88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testing Status'])[1]/preceding::select[1]</value>
      <webElementGuid>a0c0c494-abd0-4d73-b173-ba5ac9e9b048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='URL'])[1]/preceding::select[2]</value>
      <webElementGuid>af66554a-180f-4365-9a92-ac244a0fafd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/select</value>
      <webElementGuid>b4cb8596-2d20-43d4-b589-5096f67d7947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'businessImpact' and (text() = 'Please selectLOWMEDIUMHIGHCRITICAL' or . = 'Please selectLOWMEDIUMHIGHCRITICAL')]</value>
      <webElementGuid>06fd8418-02da-4ca3-9a03-ec7a7e3eb5fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
