<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Orgin filter</name>
   <tag></tag>
   <elementGuidId>201fb200-d778-4071-8747-a0ff413ff919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-component-select-Origin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mui-component-select-Origin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>512de396-8d23-4396-a0d8-02f30bd8c2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4302cc22-07d9-4c3a-aeb1-6a03ea6927ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>fd208afa-971d-4247-9c7a-2df7e945694e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>:r3i:</value>
      <webElementGuid>3acfa472-2dc0-4260-b0a5-2fcadbfa278f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06e25784-1428-4f73-8ff7-d05294f71077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>72cedd27-c005-44ea-8011-a14bebf78a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mui-component-select-Origin</value>
      <webElementGuid>d08556f0-4a56-43da-94a3-2a7d1a23fbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-component-select-Origin</value>
      <webElementGuid>c4d41db1-6633-4018-8ba3-b44e05a494cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-select MuiSelect-standard MuiSelect-multiple MuiInputBase-input MuiInput-input css-1cccqvr</value>
      <webElementGuid>47e2bab7-72a2-40d3-99d4-a960ae2efa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>37203e41-72e4-471c-aef7-c5065eb5c1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-component-select-Origin&quot;)</value>
      <webElementGuid>8e9db669-0fc8-4ad3-bf73-597566fc4f49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mui-component-select-Origin']</value>
      <webElementGuid>a7405ed1-df23-474f-a430-583bf59cbeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Origin'])[2]/following::div[2]</value>
      <webElementGuid>0148c47a-f6ac-4fed-9be6-3f71bc89d6ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESET'])[1]/following::div[6]</value>
      <webElementGuid>12602fef-264f-427c-b491-c1c5e7769c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[2]/preceding::div[1]</value>
      <webElementGuid>98c64467-5737-4b3d-b335-82db5a1cb9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div</value>
      <webElementGuid>9ecaa10e-e9c9-44fd-a704-81879f9b2668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mui-component-select-Origin' and (text() = '​' or . = '​')]</value>
      <webElementGuid>80afb7e7-3f29-4088-941a-2aa76edbf046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
