<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Files</name>
   <tag></tag>
   <elementGuidId>3cba3d17-0096-44b1-b216-9fb8c93cc925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputFile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputFile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6060547-0e17-462c-8709-9912eaa9652c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm white-input</value>
      <webElementGuid>ae5ddca5-dfb4-4639-b992-6f9e9c547599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputFile</value>
      <webElementGuid>add06ed4-d34e-4014-8340-2a89d20d0cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>3fc6e501-c7c7-47b4-95f0-d7041f1a95ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Upload file(s)</value>
      <webElementGuid>e37db453-6ee8-42fd-8742-8f3393f3da8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>9854a66d-1edf-4798-ad06-ef5c87ec5c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.png,.jpeg,.jpg,.doc,.docx,.gif,.pdf,.txt,.ppt,.xls,.xlsx,.zip</value>
      <webElementGuid>264f0e19-12f9-491c-bd81-be1d35c7a016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputFile&quot;)</value>
      <webElementGuid>e2dc8bec-1ca9-4f52-858e-065ccb1c1172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputFile']</value>
      <webElementGuid>5683c672-0967-45c5-9785-bff91b939cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[6]/input</value>
      <webElementGuid>ac3bd324-0f1f-4cd2-aa3a-cf68e6c62d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>645a5cec-7cef-422f-b51d-c114b5b25bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputFile' and @type = 'file' and @placeholder = 'Upload file(s)']</value>
      <webElementGuid>ca782bb1-53b0-4a27-9118-34ba50a7fa00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
