<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Assigned To</name>
   <tag></tag>
   <elementGuidId>a9a03679-3a9a-40cc-a160-5ae6efcfd81d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#assignedTo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='assignedTo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ff93d912-aed5-40b3-bbba-86590b46017a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assignedTo</value>
      <webElementGuid>8221adcf-9c4e-4914-b8df-bf67af9e7123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select white-input</value>
      <webElementGuid>2146a931-2a9f-4c5c-808c-2250b62d403b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test lab automate  (automatetestlab@intrucept.com)</value>
      <webElementGuid>b955b62c-d111-409e-bc15-186d555d34eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignedTo&quot;)</value>
      <webElementGuid>61f3ba4b-004f-4e45-86c1-5969f1762a72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='assignedTo']</value>
      <webElementGuid>ec5152f9-0951-48e3-9251-ffce633f508b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[5]/select</value>
      <webElementGuid>6f6bffed-1ddd-48f5-a4b0-850ae4588565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assigned To'])[1]/following::select[1]</value>
      <webElementGuid>079d13c6-a2c0-431a-a987-070d3d06c593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::select[1]</value>
      <webElementGuid>1f6299f8-c5a2-4aea-bafc-b0e5bcfd4fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add file(s)'])[1]/preceding::select[1]</value>
      <webElementGuid>d76729ba-7bcd-42f5-b8ab-b2ceb7f99d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allowed types: .png, .jpeg, .jpg, .doc, .docx, .gif, .pdf, .txt, .ppt, .xls, .xlsx, .zip, .csv'])[1]/preceding::select[1]</value>
      <webElementGuid>c133d291-72ef-43d5-ba23-ba115439e7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>2a4571dd-a035-401c-8aab-354f4a9bd90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'assignedTo' and (text() = 'Test lab automate  (automatetestlab@intrucept.com)' or . = 'Test lab automate  (automatetestlab@intrucept.com)')]</value>
      <webElementGuid>be4c2489-5acb-46db-b9e5-30eb400e846e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
