<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Business Unit</name>
   <tag></tag>
   <elementGuidId>76531f0e-80e1-444d-b0f3-0707dcee6aaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessUnit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='businessUnit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fdf75e8a-fe8f-45b4-b06f-89fccaa1514e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessUnit</value>
      <webElementGuid>40c1f0d4-b02a-473c-a1cc-0ad140354c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select white-input</value>
      <webElementGuid>0a8f16e8-f2d3-43ae-b702-04c8aedc5aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessUnit&quot;)</value>
      <webElementGuid>ab0444eb-63dd-4587-93ae-f4b5e8afad36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='businessUnit']</value>
      <webElementGuid>d7456076-628c-464f-a39e-62c55ce1a7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[7]/select</value>
      <webElementGuid>a1aa10c0-98e2-4fd1-82fd-66b6e9a6f8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/select</value>
      <webElementGuid>fa67c751-dfbb-46a7-a441-0fd462666f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'businessUnit']</value>
      <webElementGuid>dbc34306-a6d4-435a-8d8f-85da8277f138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
