<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload the project zip</name>
   <tag></tag>
   <elementGuidId>1a2e6dc3-5097-4545-93da-aad1e5217a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputFile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputFile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f46b52e-6634-4665-b427-d1b86353455e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm white-input</value>
      <webElementGuid>8d64603c-7f48-4f6d-a388-18f63d42c756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputFile</value>
      <webElementGuid>82a4d79c-79ca-4d90-a629-16b432669f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>2632eefa-a552-4932-8c20-1c5d5f9cbede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Upload project zip file</value>
      <webElementGuid>709906c7-de28-4543-8290-9abb12a68ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>1410bfd1-1b66-4b10-93af-a760c00b7711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/zip</value>
      <webElementGuid>1d1b4ef6-d2f1-47fa-adfe-cb24903b39ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputFile&quot;)</value>
      <webElementGuid>ac934d1a-ba79-403f-b60d-bf593918eb4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputFile']</value>
      <webElementGuid>eebfc784-c145-4bd4-874c-4a5f46675ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[3]/input</value>
      <webElementGuid>9eed194a-a5a6-47cd-a774-b3f00a644639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>759ef75e-1942-4a10-a2ca-1c70013907db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputFile' and @type = 'file' and @placeholder = 'Upload project zip file']</value>
      <webElementGuid>8679f829-ce85-4041-9716-8e278b4608a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
