<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Application</name>
   <tag></tag>
   <elementGuidId>d0c33034-c6ba-44df-81ff-3b3a91cf82df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scanType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='scanType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>05170ddf-1f29-449e-bbd7-dc9c925ab423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scanType</value>
      <webElementGuid>5635b7fb-7f05-45e0-b280-d8d776b2b553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select white-input</value>
      <webElementGuid>452da05e-bf4c-497b-b59f-5116f3d2beba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Application </value>
      <webElementGuid>39dc5e42-327c-47ea-a33f-aed9d00d8b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scanType&quot;)</value>
      <webElementGuid>30a80d5b-a5c8-4524-842c-806d91c07d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='scanType']</value>
      <webElementGuid>d257ae0a-a075-4641-b6fe-b732bf67211c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div[2]/div[2]/select</value>
      <webElementGuid>c076ccb9-f8d6-4712-950b-4dfd8aa04782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select application'])[1]/following::select[1]</value>
      <webElementGuid>8006daab-6860-49be-9e08-f4c1bf3fd556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan Name'])[1]/following::select[1]</value>
      <webElementGuid>c9914ec8-ef43-4e31-a518-1ab0f1aca468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload the project zip file'])[1]/preceding::select[1]</value>
      <webElementGuid>738cb4e0-9d44-4a0f-9b85-5458249bcb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Scan'])[1]/preceding::select[1]</value>
      <webElementGuid>6e2b02f2-5b19-439a-8991-a9d8e697aec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3b0ecad8-393c-4346-8f5b-3ed643dc963c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'scanType' and (text() = 'Select Application ' or . = 'Select Application ')]</value>
      <webElementGuid>d615cc1b-4655-48ee-8e12-29e844120c28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
